### PR TITLE
Design new design for new design for cards for hobbies

### PR DESCRIPTION
**Pull request by plusk**
I merged some files together because it was annoying to work with when trying to use variables across components (namely image and card), and I wasn't too hot on the whole "component for a single h2 tag" approach. I haven't touched the codebase for a while though, so maybe that's the way we do things now.

Quick PR to propose a different solution. I'm not too crazy about the gray border.

When you hover over the image, the border goes blue and the image fills the outer circle. The link works like any other link on the website.

### CODE REVIEW

**Comment by mariush2** [comment]
Really like this reiteration of the design from #271 . I am however getting some compile errors while running the project (might just be on my machine?). They look like this:

```
ERROR in /Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/ContactInfo.tsx(35,25):

TS2339: Property 'contactInfo' does not exist on type 'typeof import("/Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/footer.less")'.

ERROR in /Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/ContactInfo.tsx(37,27):
```

**Comment by henrikhorluck** [comment]
@mariush2 maybe do a `yarn install` and it should fix it

**Comment by oleast** [comment]
I agree om the images and the bottom link, they look great!
But I still like having the Divider bars. They work to separate the different types of content on that card, and makes them less 'squished'.

**Comment by oleast** [comment]
> Really like this reiteration of the design from #271 . I am however getting some compile errors while running the project (might just be on my machine?). They look like this:
> 
> ```
> ERROR in /Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/ContactInfo.tsx(35,25):
> 
> TS2339: Property 'contactInfo' does not exist on type 'typeof import("/Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/footer.less")'.
> 
> ERROR in /Users/Mht/Documents/dotkom/onlineweb-frontend/src/core/components/Footer/ContactInfo.tsx(37,27):
> ```

This is caused by the auto generated type-definition files for the `less` files not existing before running the project.

**Pull request merged**
