### PR TITLE
Add a Link which takes you to the wallet page

### PR DESCRIPTION
**Pull request by kharann**
image

### CODE REVIEW

**Comment by FluidSense** [comment]
What are your thought on having Saldo in the dropdown menu vs. at the profile page?

**Comment by kharann** [comment]
> 
> 
> What are your thought on having Saldo in the dropdown menu vs. at the profile page?


I didn't feel there was a spot in profile which made sense to have wallet. It's also its own page, so it should just be a redirect link, rather than pages directly under profile. You could maybe move it to profile, or not

**Comment by FluidSense** [comment]
In my mind, you add money to your account, and thus is a part of the profile/account. This might just be how I think about it because that was how OW4 did it. The page's content could be probably put as a subpage of the profile as well. But I agree that for now, since it is it's own page, it can be a link right there.

**Review by FluidSense — APPROVED** [review]
yup yup 👍

**Comment by kharann** [comment]
I agree moving it to a subpage in the future

**Pull request merged**
