### PR TITLE
Fix content being pushed outside body on smaller screens

### PR DESCRIPTION
**Pull request by Mattis52**
This seems to fix the sidescrolling issue on mobile while still retaining about the same layout. Works all the way down to 360px width on my machine/phone (Galaxy S8).

### CODE REVIEW

**Comment by oleast** [comment]
Thank you very much for the contribution!

Could you please provide some before and after images for the change? :smile:

**Comment by oleast** [comment]
This PR has gone stale, and without comment from the contributor (@Mattis52) for 3 months. Will close on Wednesday (27.02.2019) if no further progress is made.

**Comment by Mattis52** [comment]
### Top of homepage - before:
screenshot_20190222-143615_firefox

### Top of homepage - after: (not possible to scroll to the right)
screenshot_20190222-141849_firefox

### Bottom of homepage - before: (the arrow is pushed outside the body)
screenshot_20190222-143624_firefox

### Bottom of homepage - after:
screenshot_20190222-141331_firefox

#### Additional comparison:
screenshot_20190222-141315_firefox

**Comment by Mattis52** [comment]
:smile: :+1: Next time I will upload pictures when creating the pull request!

**Comment by oleast** [comment]
We should probably list it in the issue template to make it easier for new contributors 😛

**Comment by niklasmh** [comment]
Changing the padding in the top had unintended consequences:
image
image

I will create another issue to solve this.

@Mattis52 You did a great job, though! Seems like some screen resolutions did not handle the content on the front page very well. Nice you noticed. I will inverstigate this issue further. Anyway, continue contributing! We would not have discovered this otherwise.

**Pull request merged**
