### PR TITLE
Remove text transform to fix captialized words which should not be capitalized

### LINKED ISSUE #428: Capitalized Letters In Event Status Text.
**Describe the bug**  
Status text "Du Må Være Logget Inn For Å Se Din Status." on events have capitalized first letters, that's not a Norwegian way to type it.

**To Reproduce**
1. Go to any event while not logged in
2. Look at the text. Look at it.

**Expected behavior**
Only the word "Du" to have a capitalized first letter.

### PR DESCRIPTION
**Pull request by tokongs**
# Changes
* Add style to the specific p tag which should not be capitalized.

Fixes #428

### CODE REVIEW

**Review by kharann — DISMISSED** [review]
There are quite a few other `<p>` tags which could need this same change too. I would maybe make a css-class and apply this className to all of the p tags.  (same file)

**Comment by tokongs** [comment]
@kharann I don't think the other p tags that aren't supposed to be are affected by the capitalization.

**Comment by oleast** [comment]
Instead of force-removing the style inline, should it not just be removed from the CSS?
https://github.com/dotkom/onlineweb-frontend/blob/c04dd2016ea85ba68e77d67a26d03fdbe0feb6a7/src/events/components/DetailView/detail.less#L69

**Comment by tokongs** [comment]
@oleast I think it sort of makes sense to have it, as it captializes the data and stuff.

**Comment by FluidSense** [comment]
I think there are multiple <p>-tags that are affected by this, I seem to recall reading "Du Er Nr 16 På Venteliste" which feels an awfully lot like 
4hr8vf

I think I support @oleast's suggestion of removing the rule, and rather create a class-rule or something which can be applied to the ones where we actually want it, to avoid confusion when creating new <p>-tags inside the DetailView

**Comment by kharann** [comment]
> I think there are multiple `<p>`-tags that are affected by this, I seem to recall reading "Du Er Nr 16 På Venteliste" which feels an awfully lot like
> 4hr8vf
> 
> I think I support @oleast's suggestion of removing the rule, and rather create a class-rule or something which can be applied to the ones where we actually want it, to avoid confusion when creating new `<p>`-tags inside the`DetailView`

Takk Johannes

**Comment by tokongs** [comment]
@FluidSense That sounds like a good plan, is the way it's done now the right way to do it?

**Review by FluidSense — APPROVED** [review]
Nice!

**Pull request merged**
